# /app/config/serivces.yml
# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    security.authentication.success_handler.class: AppBundle\Security\Authentication\Handler\LoginSuccessHandler
    security.authentication.failure_handler.class: AppBundle\Security\Authentication\Handler\LoginFailureHandler
    

services:
    login_success_handler:
        class:  %security.authentication.success_handler.class%
        public: false
        arguments: ['@router', '@fos_user.user_manager', '@security.authorization_checker']
        tags:
            - { name: 'monolog.logger', channel: 'security' }
        
    login_failure_handler:
        class: %security.authentication.failure_handler.class%
        public: false
        arguments: ['@http_kernel', '@security.http_utils', {}, '@logger', '@router', '@fos_user.user_manager', '@service_container']
        tags:
            - { name: 'monolog.logger', channel: 'security' }
        
    app.form.registration:
        class: AppBundle\Form\RegistrationFormType
        tags:
            - { name: "form.type", alias: "app_user_registration" }

    app.form.invitation:
        class: AppBundle\Form\InvitationFormType
        arguments: ['@app.form.data_transformer.invitation']
        tags:
            - { name: "form.type", alias: "app_invitation_type" }

    app.form.data_transformer.invitation:
        class: AppBundle\Form\DataTransformer\InvitationToCodeTransformer
        arguments: ['@doctrine.orm.entity_manager']
        public: false
    
#    kernel.listener.database_switcher:
#        class: AppBundle\EventListener\DatabaseSwitcher
#        arguments:  [@request, @doctrine.dbal.default_connection, @logger]
#        scope:      request
#        tags:
#            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }